// Temporary sample data. We'll replace it with real data from the backend later.
export const DRIVERS = [
    {
        id: "#GS-10250",
        initials: "MP",
        name: "Mateus Pacheco",
        status: "in_transit",
        eta: "6:07 pm",
        stopsLeft: 5,
        parcels: 12,
        note: "On time",
        progress: 58,
    },
    {
        id: "#GS-10291",
        initials: "JR",
        name: "João Ribeiro",
        status: "delayed",
        eta: "+28 min",
        stopsLeft: 8,
        parcels: 20,
        note: "Traffic delay",
        progress: 32,
    },
    {
        id: "#GS-10215",
        initials: "AF",
        name: "Ana Ferreira",
        status: "completed",
        eta: "Done",
        stopsLeft: 0,
        parcels: 18,
        note: "",
        progress: 100,
    },
    {
        id: "#GS-10308",
        initials: "TG",
        name: "Tomás Garcia",
        status: "in_transit",
        eta: "7:45 pm",
        stopsLeft: 11,
        parcels: 24,
        note: "",
        progress: 19,
    },
    {
        id: "#GS-10334",
        initials: "LS",
        name: "Lena Sousa",
        status: "in_transit",
        eta: "6:52 pm",
        stopsLeft: 4,
        parcels: 9,
        note: "",
        progress: 45,
    },
];